version: "3"
services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile 
  #   ports:
  #     - "7007:7007"
  #   volumes:
  #     - .:/code
  #   environment:
  #    - PORT=3307
  #    - MYSQL_PASSWORD=mauFJcuf5dhRMQrjj
  #    - MYSQL_USER=OL_user
  #    - MYSQL_DATABASE=main

  database:
    image: mariadb:10.7
    networks:
      - app-tier
    ports:
      - 3307:3306
    volumes:
      - .:/db
      #- ./mariadb-data:/var/lib/mysql
      #- ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=mauFJcuf5dhRMQrjj
      - MYSQL_USER=OL_user
      - MYSQL_DATABASE=main
      
networks:
    app-tier:
        driver: bridge

